### ISSUE TITLE
"Unknown current version number" message remains after update ("SOURCE" install type)

### ISSUE THREAD

**Issue by willemw12** [SickRage/sickrage-issues#118]
After updating package https://aur.archlinux.org/packages/sickrage2-git to the latest version 4.2.0.6 (2015-11-28), the version check warning remains:

    Unknown current version number: If you've never used the SickRage upgrade system before then current version is not set.— Update Now

Install type is "SOURCE":

    INFO     CHECKVERSION :: Checking for updates using SOURCE

File config.ini:

    cur_commit_hash = ""

**Comment by djack42** [comment]
Same here but with manual update from github.
Updating again works, but same problem.
I must have 1e8a1a0ede9b386f25e243c1c4e3814a520bd325 but i can't be sure

**Comment by miigotu** [comment]
This was already fixed in develop. Will merge to master as soon as we test a bit more.

**Comment by djack42** [comment]
Not fixed for mem I just updated and the message is still here.
No warning, log says
2015-12-03 17:12:59 DEBUG    CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2015-12-03 17:12:59 DEBUG    CHECKVERSION :: Unknown current version number, don't know if we should update or not
2015-12-03 17:12:59 DEBUG    CHECKVERSION :: cur_commit = , newest_commit = a89bf7fbf5dd0762d1d6ac98cd624219697a6a54, num_commits_behind = 0

**Comment by miigotu** [comment]
its definitely fixed. maybe you aren't really using this fork? check your status page
