### ISSUE TITLE
Subtitles Extra Scripts input gets erased when saving settings

### ISSUE THREAD

**Issue by eucalyptus30** [SickRage/sickrage-issues#76]
- Branch  <b>Master</b>
 - Python Version <b>2.7.9</b>
 - Operating System <b>Debian GNU/Linux 8.2 (jessie)</b>
 - Commit hash <b>d294e9faf48d45051a50d4e2cf3a0252c28d5b17</b>

#### What you did
Add an Extra Scripts when a subtitle is downloaded.
#### What happened
When i reload the "Subtitles settings" page.
The extra scripts input is empty and yet, i had the notification "Configuration Saved"
And all subtitle Plugins are disable after that. Like if my Subtitle configuration was reset.

My extra script command is : /usr/bin/php5 /var/www/dc3/advanced/yii serietvauto/serieended

Even if the extra script is blank, it seems that sickrage try to execute the extra script. But an error occurred.
```
2015-11-20 01:51:34 INFO     POSTPROCESSER :: Error occurred when downloading subtitles for: /home/download/SeriesTV/Once Upon a Time (2011)/Season 05/Once Upon a Time (2011) - S05E09 720p.HDTV-KILLERS.mkv
2015-11-20 01:51:34 ERROR    POSTPROCESSER :: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/subtitles.py", line 155, in downloadSubtitles
    run_subs_extra_scripts(subtitles_info, found_subtitles)
  File "/opt/SickRage/sickbeard/subtitles.py", line 444, in run_subs_extra_scripts
    for video, subs in foundSubs.iteritems():
AttributeError: 'list' object has no attribute 'iteritems'
```
It seems that i've two problem.
 - The lost of my extra script setting.
 - And error when sickrage try to execute the extra script.

I don't know if it's linked. 

Full log : 
https://dl.dropboxusercontent.com/u/27751092/sickrage.log
https://dl.dropboxusercontent.com/u/27751092/sickrage.log.1

**Comment by OmgImAlexis** [comment]
@medariox

**Comment by medariox** [comment]
You are using an extremely outdated SR version. This has been fixed in master since 2+ weeks. Please update.

**Comment by eucalyptus30** [comment]
Ho i'm so sorry.

Okay, i've done a full git clone from the master.
Now, i've : 
<b>SR Version:	BRANCH: (master) / COMMIT: (91e54c0364df98358a01436ee247a348775e88e1) </b>

but if i set "/usr/bin/php5 /var/www/dc3/advanced/yii serietvauto/serieendedsub" to the "Extra Scripts" input.
And Then i click on "Save Changes" and after that i refresh the page. Extra Scripts input is empty and i've lost my setting in "Subtitle Plugins" tab.

am i the only one having this problem ?

**Comment by labrys** [comment]
We are currently looking at a few things in the UI and this may or may not be related, can you confirm that you are still getting errors now?  Or is the field just blank?  If you continue to get errors, please provide us with an updated log, it would help immensely.

**Comment by medariox** [comment]
This is just a visual lacking. The script path is actually added to config.ini and should be correctly executed. Also the lost settings in "Subtitle Plugins" is a known issue.

**Comment by eucalyptus30** [comment]
i confirm that it's good in the config.ini file.
```
subtitles_extra_scripts = /usr/bin/php5 /var/www/dc3/advanced/yii serietvauto/serieendedsub
```

I've done a full test and IT'S WORKING :smiley: 
I confirm that it's just  a visual lacking.

THANKS !!

**Comment by medariox** [comment]
I fixed the visual bug with https://github.com/SickRage/SickRage/pull/188 in the develop branch. To fix the other bug we will most likely have to wait for @OmgImAlexis, our JS champ!

**Comment by eucalyptus30** [comment]
I added a Pull request for fixing the lost of subtitle Plugins selection.
